#!/bin/bash -x

gtd 7853 | cat > about-commissioning-machines-7853.md
sleep 3
gtd 11432 | cat > about-commissioning-scripts-11432.md
sleep 3
gtd 6690 | cat > about-controllers-6690.md
sleep 3
gtd 7901 | cat > about-deploying-machines-7901.md
sleep 3
gtd 7903 | cat > about-deploying-running-machines-7903.md
sleep 3
gtd 7869 | cat > about-lxd-projects-7869.md
sleep 3
gtd 6510 | cat > about-maas-events-6510.md
sleep 3
gtd 5240 | cat > about-maas-logging-5240.md
sleep 3
gtd 9620 | cat > about-maas-networking-9620.md
sleep 3
gtd 6178 | cat > about-maas-performance-6178.md
sleep 3
gtd 6719 | cat > about-maas-security-6719.md
sleep 3
gtd 7917 | cat > about-machine-basics-7917.md
sleep 3
gtd 7902 | cat > about-machine-customisation-7902.md
sleep 3
gtd 11160 | cat > about-machine-groups-11160.md
sleep 3
gtd 7904 | cat > about-standard-images-7904.md
sleep 3
gtd 7847 | cat > about-the-machine-life-cycle-7847.md
sleep 3
gtd 3205 | cat > account-3205.md
sleep 3
gtd 11400 | cat > apikey-11400.md
sleep 3
gtd 6836 | cat > bcache-6836.md
sleep 3
gtd 11401 | cat > bcache-cache-set-11401.md
sleep 3
gtd 2357 | cat > block-device-2357.md
sleep 3
gtd 11355 | cat > boot-resource-11355.md
sleep 3
gtd 6850 | cat > boot-source-6850.md
sleep 3
gtd 11402 | cat > boot-source-selection-11402.md
sleep 3
gtd 11380 | cat > changepassword-11380.md
sleep 3
gtd 6605 | cat > commissioning-scripts-6605.md
sleep 3
gtd 11403 | cat > config-11403.md
sleep 3
gtd 11378 | cat > configauth-11378.md
sleep 3
gtd 11351 | cat > config-tls-11351.md
sleep 3
gtd 8035 | cat > configuration-reference-8035.md
sleep 3
gtd 11348 | cat > config-vault-11348.md
sleep 3
gtd 11379 | cat > createadmin-11379.md
sleep 3
gtd 11356 | cat > device-11356.md
sleep 3
gtd 11357 | cat > dhcpsnippet-11357.md
sleep 3
gtd 758 | cat > discovery-758.md
sleep 3
gtd 11352 | cat > dnsresource-11352.md
sleep 3
gtd 11404 | cat > dnsresource-record-11404.md
sleep 3
gtd 11405 | cat > domain-11405.md
sleep 3
gtd 6373 | cat > events-6373.md
sleep 3
gtd 6141 | cat > explanation-6141.md
sleep 3
gtd 11359 | cat > fabric-11359.md
sleep 3
gtd 11360 | cat > file-11360.md
sleep 3
gtd 5060 | cat > how-to-authenticate-to-the-maas-api-5060.md
sleep 3
gtd 5096 | cat > how-to-back-up-maas-5096.md
sleep 3
gtd 7873 | cat > how-to-build-an-ubuntu-image-7873.md
sleep 3
gtd 7872 | cat > how-to-build-maas-images-7872.md
sleep 3
gtd 5973 | cat > how-to-configure-storage-layouts-5973.md
sleep 3
gtd 5448 | cat > how-to-contact-us-5448.md
sleep 3
gtd 6949 | cat > how-to-contribute-to-maas-documentation-6949.md
sleep 3
gtd 7896 | cat > how-to-create-custom-storage-7896.md
sleep 3
gtd 7743 | cat > how-to-deploy-a-fips-compliant-kernel-7743.md
sleep 3
gtd 6658 | cat > how-to-deploy-a-real-time-kernel-6658.md
sleep 3
gtd 7885 | cat > how-to-deploy-vms-on-ibm-z-7885.md
sleep 3
gtd 5196 | cat > how-to-enhance-maas-security-5196.md
sleep 3
gtd 5128 | cat > how-to-get-maas-up-and-running-5128.md
sleep 3
gtd 8833 | cat > how-to-group-machines-8833.md
sleep 3
gtd 6663 | cat > how-to-guides-6663.md
sleep 3
gtd 7893 | cat > how-to-manage-block-devices-7893.md
sleep 3
gtd 5120 | cat > how-to-manage-high-availability-5120.md
sleep 3
gtd 5124 | cat > how-to-manage-images-5124.md
sleep 3
gtd 5172 | cat > how-to-manage-machines-5172.md
sleep 3
gtd 5164 | cat > how-to-manage-networks-5164.md
sleep 3
gtd 11320 | cat > how-to-manage-network-services-11320.md
sleep 3
gtd 7894 | cat > how-to-manage-partitions-7894.md
sleep 3
gtd 7895 | cat > how-to-manage-vmfs-datastores-7895.md
sleep 3
gtd 5204 | cat > how-to-monitor-maas-5204.md
sleep 3
gtd 4446 | cat > how-to-report-and-review-bugs-4446.md
sleep 3
gtd 4447 | cat > how-to-request-features-4447.md
sleep 3
gtd 5404 | cat > how-to-script-maas-wtih-python-5404.md
sleep 3
gtd 5212 | cat > how-to-set-up-air-gapped-maas-5212.md
sleep 3
gtd 5333 | cat > how-to-troubleshoot-common-issues-5333.md
sleep 3
gtd 11178 | cat > how-to-upgrade-from-postgresql-v14-to-v16-11178.md
sleep 3
gtd 7203 | cat > how-to-upgrade-postgresql-v12-to-v14-7203.md
sleep 3
gtd 9122 | cat > how-to-use-cloud-init-with-maas-step-by-step-examples-9122.md
sleep 3
gtd 6956 | cat > how-to-use-logging-6956.md
sleep 3
gtd 11350 | cat > init-11350.md
sleep 3
gtd 11364 | cat > interface-11364.md
sleep 3
gtd 761 | cat > ipaddresses-761.md
sleep 3
gtd 760 | cat > iprange-760.md
sleep 3
gtd 11362 | cat > license-key-11362.md
sleep 3
gtd 11406 | cat > list-11406.md
sleep 3
gtd 11345 | cat > login-11345.md
sleep 3
gtd 11407 | cat > logout-11407.md
sleep 3
gtd 11408 | cat > maas-11408.md
sleep 3
gtd 6662 | cat > maas-documentation-6662.md
sleep 3
gtd 5360 | cat > maas-in-thirty-minutes-5360.md
sleep 3
gtd 10405 | cat > maas-logging-reference-10405.md
sleep 3
gtd 11365 | cat > machine-11365.md
sleep 3
gtd 11381 | cat > migrate-11381.md
sleep 3
gtd 11409 | cat > network-11409.md
sleep 3
gtd 11431 | cat > node-11431.md
sleep 3
gtd 11410 | cat > node-device-11410.md
sleep 3
gtd 11411 | cat > node-results-11411.md
sleep 3
gtd 11413 | cat > node-script-11413.md
sleep 3
gtd 11412 | cat > node-script-result-11412.md
sleep 3
gtd 11366 | cat > notification-11366.md
sleep 3
gtd 814 | cat > package-repository-814.md
sleep 3
gtd 11367 | cat > partition-11367.md
sleep 3
gtd 823 | cat > pod-823.md
sleep 3
gtd 8089 | cat > postgresql-deprecation-notices-8089.md
sleep 3
gtd 11347 | cat > profile-11347.md
sleep 3
gtd 11415 | cat > rack-controller-11415.md
sleep 3
gtd 11369 | cat > raid-11369.md
sleep 3
gtd 6143 | cat > reference-6143.md
sleep 3
gtd 6605 | cat > reference-commissioning-scripts-6605.md
sleep 3
gtd 4186 | cat > reference-documentation-style-guide-4186.md
sleep 3
gtd 5392 | cat > reference-hardware-test-scripts-5392.md
sleep 3
gtd 6233 | cat > reference-installation-requirements-6233.md
sleep 3
gtd 5416 | cat > reference-maas-glossary-5416.md
sleep 3
gtd 7268 | cat > reference-maas-metrics-7268.md
sleep 3
gtd 7898 | cat > reference-maas-storage-7898.md
sleep 3
gtd 7882 | cat > reference-power-drivers-7882.md
sleep 3
gtd 5292 | cat > reference-release-notes-5292.md
sleep 3
gtd 5993 | cat > reference-release-notes-maas-2-7-5993.md
sleep 3
gtd 5994 | cat > reference-release-notes-maas-2-8-5994.md
sleep 3
gtd 5961 | cat > reference-release-notes-maas-2-9-5961.md
sleep 3
gtd 5963 | cat > reference-release-notes-maas-3-0-5963.md
sleep 3
gtd 5964 | cat > reference-release-notes-maas-3-1-5964.md
sleep 3
gtd 5962 | cat > reference-release-notes-maas-3-2-5962.md
sleep 3
gtd 6346 | cat > reference-release-notes-maas-3-3-6346.md
sleep 3
gtd 7071 | cat > reference-release-notes-maas-3-4-7071.md
sleep 3
gtd 8086 | cat > reference-release-notes-maas-3-5-8086.md
sleep 3
gtd 6327 | cat > reference-terraform-6327.md
sleep 3
gtd 11414 | cat > refresh-11414.md
sleep 3
gtd 11344 | cat > region-controller-11344.md
sleep 3
gtd 3089 | cat > resource-pool-3089.md
sleep 3
gtd 11370 | cat > space-11370.md
sleep 3
gtd 11371 | cat > sshkey-11371.md
sleep 3
gtd 11342 | cat > ssl-key-11342.md
sleep 3
gtd 11342 | cat > sslkey-11342.md
sleep 3
gtd 11372 | cat > static-route-11372.md
sleep 3
gtd 11349 | cat > status-11349.md
sleep 3
gtd 766 | cat > subnet-766.md
sleep 3
gtd 6941 | cat > tag-6941.md
sleep 3
gtd 11374 | cat > user-11374.md
sleep 3
gtd 11341 | cat > version-11341.md
sleep 3
gtd 11375 | cat > vlan-11375.md
sleep 3
gtd 11340 | cat > vm-cluster-11340.md
sleep 3
gtd 780 | cat > vmfs-datastores-780.md
sleep 3
gtd 11376 | cat > vm-host-11376.md
sleep 3
gtd 11339 | cat > volume-group-11339.md
sleep 3
gtd 11377 | cat > zone-11377.md
sleep 3
